Repository vircadia/vircadia-web, pull requests merged in 2023-03, with the labels that each got.

#145 Fix routing after wizard.
  .eslintrc.js
  package-lock.json
  package.json
  quasar.conf.js
  src/config.ts
  src/pages/FirstTimeSetup.vue
  src/router/index.ts
  src/router/routes.ts
  src/store/index.ts
Labels: bugfix, housekeeping

#149 Add configurable Open Graph tags.
  package.json
  public/assets/OpenGraph_banner.png
  quasar.conf.js
  src/index.template.html
  src/store/index.ts
Labels: enhancement

#150 Implement functionality for mute/volume controls in the "People" menu.
  src/components/overlays/people/People.vue
  src/modules/domain/audio.ts
  src/store/index.ts
Labels: bugfix

#151 Redesign the list items in the People menu.
  src/components/MainScene.vue
  src/components/overlays/avatar/Avatar.vue
  src/components/overlays/people/People.vue
  src/modules/avatar/StoreInterface.ts
  src/modules/scene/vscene.ts
Labels: enhancement

#152 Rotate the player's avatar to face forwards when in FPV. Add a state to keep track of the player's interactions.
  src/modules/avatar/controller/inputController.ts
  src/modules/avatar/controller/inputs/keyboardInput.ts
  src/modules/entity/components/components/model.ts
  src/modules/entity/entities/NametagEntity.ts
  src/modules/scene/vscene.ts
  src/store/index.ts
Labels: bugfix

#153 Scroll just the avatar model list instead of the whole Avatar menu.
  src/components/overlays/OverlayShell.vue
  src/components/overlays/avatar/Avatar.vue
  src/modules/avatar/StoreInterface.ts
  src/modules/scene/vscene.ts
Labels: user experience

#155 Add new `sitting_couch` animation.
  public/assets/AnimationsBasic.glb
  src/modules/avatar/controller/avatarState.ts
Labels: enhancement
